apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cehs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cehs
    app.kubernetes.io/part-of: tkrw-pr714-0075-0032-app
  name: devfile-sample-cehs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cehs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cehs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0032-tenant/tkrw-pr714-0075-0032-app/devfile-sample-cehs@sha256:3581e7dc6b1dcfbbcc733fb056b2d12c8cab5efd5a829886671c15d2dbd5711c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
